### ISSUE TITLE
Auto [x, y] = simple_divide(a, b)

### ISSUE THREAD

**Issue by MoAlyousef** [hellozee/errors#1]
If you use C++17 for your library, you can profit from structured binding declaration as above:
https://en.cppreference.com/w/cpp/language/structured_binding

You also won’t need the std::get<index> expression.

**Comment by hellozee** [comment]
@MoAlyousef yes I took a look there when I was writing the example initially but now that I wrote a container, I think that can be avoided, though that a nice strategy too
